let visiTor= prompt('Hello, is this your first visit?');
let userNam= prompt('Please enter your name...');
let eGe= prompt('Please enter your age...');
let commEnt= prompt('I hope I do well. Please enter your comment..');
alert ('Hi ' + userNam +  eGe + 'old' + ' you are welcome ' + ' thanks for your comment ' + commEnt );
console.log('Hi ' + userNam + ' you are welcome ' + ' thanks for your comment ' + commEnt);
//document.write( '<p>' + 'Hello, is this your first visit?' +visiTor + '</p>');
//document.write( '<p>' + 'Please enter your name...' + userNam + '</p>');
//document.write( '<p>' + 'Please enter your age...' + eGe + '</p>');
//document.write( '<p>' + 'I hope I do well. Please enter your comment..' + commEnt + '</p>');
document.write( userNam + ' thanks for your comment ');